# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: RedgateSqlChangeAutomationBuild@4
  inputs:
    operation: 'Build'
    dbFolder: 'RootFolder'
    packageName: 'BeepBeep_Database'
    tempServerTypeBuild: 'localDB'
    nugetPackageVersionSelector: 'Specific'
    nugetPackageVersion: '1.0'
    nugetPackageVersionUseBuildId: true
    requiredVersionOfDlma: 'latest'

- task: OctopusPush@4
  inputs:
    OctoConnectedServiceName: 'BeepBeepEnterprise'
    Space: 'Spaces-22'
    Package: 'BeepBeep_Database.1.0.{Release.ReleaseID}.nupkg'
    Replace: 'false'